[package]
edition = "2021"
name = "gossip"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.64"
bincode = "1.3.3"
crossbeam-channel = "0.5.6"
if-addrs = "0.8.0"
mdns-sd = {version = "0.5.10", features = ["async"]}
rand = "0.8.5"
serde = "1.0.152"
serde_derive = "1.0.152"
tokio = {version = "1.25.0", features = ["full"]}
uuid = {version = "1.3.0", features = ["serde", "v4"]}
